context:
  version: "3.14.2.0"

package:
  name: cabal
  version: ${{ version }}

source:
  - url: https://github.com/haskell/cabal/archive/refs/tags/cabal-install-v${{ version }}.tar.gz
    sha256: c24784c3cfaea08f7a0cfcddba31672044dcab59f5c6bb58a82ddc7e4310badc

  - if: linux
    then:
      url: https://downloads.haskell.org/~cabal/cabal-install-${{ version }}/cabal-install-${{ version }}-x86_64-linux-ubuntu20_04.tar.xz
      sha256: 974a0c29cae721a150d5aa079a65f2e1c0843d1352ffe6aedd7594b176c3e1e6
      target_directory: cabal-bootstrap
  - if: osx
    then:
      url: https://downloads.haskell.org/~cabal/cabal-install-${{ version }}/cabal-install-${{ version }}-x86_64-darwin.tar.xz
      sha256: f9d0cac59deeeb1d35f72f4aa7e5cba3bfe91d838e9ce69b8bc9fc855247ce0f
      target_directory: cabal-bootstrap
  - if: not unix
    then:
      url: https://downloads.haskell.org/~cabal/cabal-install-${{ version }}/cabal-install-${{ version }}-x86_64-windows.zip
      sha256: 7b97779519f7c4e86d7a87ff2ec57777c17ca69389b968f363fbfbdbf4ae8536
      target_directory: cabal-bootstrap
    

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - perl
    - pkg-config
    - curl
    - ghc-bootstrap
    - if: unix
      then:
        - file
        - tar
        - xz-tools
      else:
        - binutils
        - m2-bash
        - m2-coreutils
        - m2-diffutils
        - m2-file
        - m2-gawk
        - m2-grep
        - m2-unzip
        - m2-which
  host:
    - if: linux
      then:
        - gmp
        - zlib
    - if: osx
      then:
        - libiconv

tests:
  - script: |
      cabal --version

about:
  homepage: https://github.com/haskell/cabal
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'cabal-install is the command line interface to Cabal and hackage.'
  documentation: https://www.haskell.org/cabal/index.html
  repository: https://github.com/haskell/cabal

extra:
  recipe-maintainers:
    - MementoRC
    - eggzilla
