context:
  version: "3.14.1.1"

package:
  name: cabal
  version: ${{ version }}

source:
  - url: https://github.com/haskell/cabal/archive/refs/tags/cabal-install-v${{ version }}.tar.gz
    sha256: a79d90a4eefa1c55d10db78e252d5ea7fdf057bdb6bb7ab54743aec77208b506

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - perl
    - pkg-config
    - curl
    - ghc-bootstrap
    - if: unix
      then:
        - file
        - tar
        - xz-tools
      else:
        - binutils
        - m2-bash
        - m2-coreutils
        - m2-diffutils
        - m2-file
        - m2-gawk
        - m2-grep
        - m2-unzip
        - m2-which
  host:
    - gmp
    - libiconv
    - libffi
    - zlib

tests:
  - script: |
      cabal --version
    # requirements:
    #   run:
    #     - libiconv

about:
  homepage: https://github.com/haskell/cabal
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'cabal-install is the command line interface to Cabal and hackage.'
  documentation: https://www.haskell.org/cabal/index.html
  repository: https://github.com/haskell/cabal

extra:
  recipe-maintainers:
    - eggzilla
