context:
  version: "3.14.1.1"
  ghc_version: "9.10.2"

package:
  name: cabal
  version: ${{ version }}

source:
  - url: https://github.com/haskell/cabal/archive/refs/tags/cabal-install-v${{ version }}.tar.gz
    sha256: a79d90a4eefa1c55d10db78e252d5ea7fdf057bdb6bb7ab54743aec77208b506 3.14.1.1

build:
  number: 0
  script:
    env:
      GHC_VERSION: ${{ ghc_version }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - perl
    - pkg-config
    - curl
    - ghc ==${{ ghc_version }}
  host:
    - gmp
    - libiconv
    - libffi
    - zlib
  run:

tests:
  - script: |
      cabal --version

about:
  homepage: https://github.com/haskell/cabal
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'cabal-install is the command line interface to Cabal and hackage.'
  documentation: https://www.haskell.org/cabal/index.html
  repository: https://github.com/haskell/cabal

extra:
  recipe-maintainers:
    - eggzilla
